/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MapsIndexRouteImport } from './routes/maps/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as AuditLogIndexRouteImport } from './routes/audit-log/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as MapsNewIndexRouteImport } from './routes/maps/new/index'
import { Route as MapsMapIdIndexRouteImport } from './routes/maps/$mapId/index'
import { Route as DataMapIdIndexRouteImport } from './routes/data/$mapId/index'
import { Route as MapsMapIdSourceRouteImport } from './routes/maps/$mapId/source'
import { Route as MapsMapIdExportRouteImport } from './routes/maps/$mapId/export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsIndexRoute = MapsIndexRouteImport.update({
  id: '/maps/',
  path: '/maps/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogIndexRoute = AuditLogIndexRouteImport.update({
  id: '/audit-log/',
  path: '/audit-log/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsNewIndexRoute = MapsNewIndexRouteImport.update({
  id: '/maps/new/',
  path: '/maps/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapIdIndexRoute = MapsMapIdIndexRouteImport.update({
  id: '/maps/$mapId/',
  path: '/maps/$mapId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataMapIdIndexRoute = DataMapIdIndexRouteImport.update({
  id: '/data/$mapId/',
  path: '/data/$mapId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapIdSourceRoute = MapsMapIdSourceRouteImport.update({
  id: '/maps/$mapId/source',
  path: '/maps/$mapId/source',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapIdExportRoute = MapsMapIdExportRouteImport.update({
  id: '/maps/$mapId/export',
  path: '/maps/$mapId/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/audit-log/': typeof AuditLogIndexRoute
  '/data/': typeof DataIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/maps/$mapId/export': typeof MapsMapIdExportRoute
  '/maps/$mapId/source': typeof MapsMapIdSourceRoute
  '/data/$mapId/': typeof DataMapIdIndexRoute
  '/maps/$mapId/': typeof MapsMapIdIndexRoute
  '/maps/new/': typeof MapsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/audit-log': typeof AuditLogIndexRoute
  '/data': typeof DataIndexRoute
  '/maps': typeof MapsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/maps/$mapId/export': typeof MapsMapIdExportRoute
  '/maps/$mapId/source': typeof MapsMapIdSourceRoute
  '/data/$mapId': typeof DataMapIdIndexRoute
  '/maps/$mapId': typeof MapsMapIdIndexRoute
  '/maps/new': typeof MapsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/audit-log/': typeof AuditLogIndexRoute
  '/data/': typeof DataIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/maps/$mapId/export': typeof MapsMapIdExportRoute
  '/maps/$mapId/source': typeof MapsMapIdSourceRoute
  '/data/$mapId/': typeof DataMapIdIndexRoute
  '/maps/$mapId/': typeof MapsMapIdIndexRoute
  '/maps/new/': typeof MapsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/'
    | '/audit-log/'
    | '/data/'
    | '/maps/'
    | '/settings/'
    | '/maps/$mapId/export'
    | '/maps/$mapId/source'
    | '/data/$mapId/'
    | '/maps/$mapId/'
    | '/maps/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit-log'
    | '/data'
    | '/maps'
    | '/settings'
    | '/maps/$mapId/export'
    | '/maps/$mapId/source'
    | '/data/$mapId'
    | '/maps/$mapId'
    | '/maps/new'
  id:
    | '__root__'
    | '/'
    | '/about/'
    | '/audit-log/'
    | '/data/'
    | '/maps/'
    | '/settings/'
    | '/maps/$mapId/export'
    | '/maps/$mapId/source'
    | '/data/$mapId/'
    | '/maps/$mapId/'
    | '/maps/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AuditLogIndexRoute: typeof AuditLogIndexRoute
  DataIndexRoute: typeof DataIndexRoute
  MapsIndexRoute: typeof MapsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  MapsMapIdExportRoute: typeof MapsMapIdExportRoute
  MapsMapIdSourceRoute: typeof MapsMapIdSourceRoute
  DataMapIdIndexRoute: typeof DataMapIdIndexRoute
  MapsMapIdIndexRoute: typeof MapsMapIdIndexRoute
  MapsNewIndexRoute: typeof MapsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/': {
      id: '/maps/'
      path: '/maps'
      fullPath: '/maps/'
      preLoaderRoute: typeof MapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log/': {
      id: '/audit-log/'
      path: '/audit-log'
      fullPath: '/audit-log/'
      preLoaderRoute: typeof AuditLogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/new/': {
      id: '/maps/new/'
      path: '/maps/new'
      fullPath: '/maps/new/'
      preLoaderRoute: typeof MapsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapId/': {
      id: '/maps/$mapId/'
      path: '/maps/$mapId'
      fullPath: '/maps/$mapId/'
      preLoaderRoute: typeof MapsMapIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$mapId/': {
      id: '/data/$mapId/'
      path: '/data/$mapId'
      fullPath: '/data/$mapId/'
      preLoaderRoute: typeof DataMapIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapId/source': {
      id: '/maps/$mapId/source'
      path: '/maps/$mapId/source'
      fullPath: '/maps/$mapId/source'
      preLoaderRoute: typeof MapsMapIdSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapId/export': {
      id: '/maps/$mapId/export'
      path: '/maps/$mapId/export'
      fullPath: '/maps/$mapId/export'
      preLoaderRoute: typeof MapsMapIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  AuditLogIndexRoute: AuditLogIndexRoute,
  DataIndexRoute: DataIndexRoute,
  MapsIndexRoute: MapsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  MapsMapIdExportRoute: MapsMapIdExportRoute,
  MapsMapIdSourceRoute: MapsMapIdSourceRoute,
  DataMapIdIndexRoute: DataMapIdIndexRoute,
  MapsMapIdIndexRoute: MapsMapIdIndexRoute,
  MapsNewIndexRoute: MapsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
