/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MapsIndexRouteImport } from './routes/maps/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as MapsNewIndexRouteImport } from './routes/maps/new/index'
import { Route as MapsMapIdIndexRouteImport } from './routes/maps/$mapId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsIndexRoute = MapsIndexRouteImport.update({
  id: '/maps/',
  path: '/maps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsNewIndexRoute = MapsNewIndexRouteImport.update({
  id: '/maps/new/',
  path: '/maps/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapIdIndexRoute = MapsMapIdIndexRouteImport.update({
  id: '/maps/$mapId/',
  path: '/maps/$mapId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/maps/$mapId/': typeof MapsMapIdIndexRoute
  '/maps/new/': typeof MapsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/maps': typeof MapsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/maps/$mapId': typeof MapsMapIdIndexRoute
  '/maps/new': typeof MapsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/maps/$mapId/': typeof MapsMapIdIndexRoute
  '/maps/new/': typeof MapsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/'
    | '/maps/'
    | '/settings/'
    | '/maps/$mapId/'
    | '/maps/new/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/maps' | '/settings' | '/maps/$mapId' | '/maps/new'
  id:
    | '__root__'
    | '/'
    | '/about/'
    | '/maps/'
    | '/settings/'
    | '/maps/$mapId/'
    | '/maps/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  MapsIndexRoute: typeof MapsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  MapsMapIdIndexRoute: typeof MapsMapIdIndexRoute
  MapsNewIndexRoute: typeof MapsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/': {
      id: '/maps/'
      path: '/maps'
      fullPath: '/maps/'
      preLoaderRoute: typeof MapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/new/': {
      id: '/maps/new/'
      path: '/maps/new'
      fullPath: '/maps/new/'
      preLoaderRoute: typeof MapsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapId/': {
      id: '/maps/$mapId/'
      path: '/maps/$mapId'
      fullPath: '/maps/$mapId/'
      preLoaderRoute: typeof MapsMapIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  MapsIndexRoute: MapsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  MapsMapIdIndexRoute: MapsMapIdIndexRoute,
  MapsNewIndexRoute: MapsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
