/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthGithubRouteImport } from './routes/auth/github'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardPgliteLayoutRouteImport } from './routes/_dashboard/pglite/layout'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardPgliteIndexRouteImport } from './routes/_dashboard/pglite/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthGithubRoute = AuthGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardPgliteLayoutRoute = DashboardPgliteLayoutRouteImport.update({
  id: '/pglite',
  path: '/pglite',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardPgliteIndexRoute = DashboardPgliteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPgliteLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/pglite': typeof DashboardPgliteLayoutRouteWithChildren
  '/dashboard': typeof DashboardDashboardRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/test/': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pglite/': typeof DashboardPgliteIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth': typeof AuthIndexRoute
  '/test': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pglite': typeof DashboardPgliteIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/_dashboard/pglite': typeof DashboardPgliteLayoutRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/test/': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/pglite/': typeof DashboardPgliteIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pglite'
    | '/dashboard'
    | '/auth/github'
    | '/auth/signup'
    | '/auth/'
    | '/test/'
    | '/api/auth/$'
    | '/pglite/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/github'
    | '/auth/signup'
    | '/auth'
    | '/test'
    | '/api/auth/$'
    | '/pglite'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/pglite'
    | '/_dashboard/dashboard'
    | '/auth/github'
    | '/auth/signup'
    | '/auth/'
    | '/test/'
    | '/api/auth/$'
    | '/_dashboard/pglite/'
    | '/_dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  TestIndexRoute: typeof TestIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/github': {
      id: '/auth/github'
      path: '/github'
      fullPath: '/auth/github'
      preLoaderRoute: typeof AuthGithubRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/pglite': {
      id: '/_dashboard/pglite'
      path: '/pglite'
      fullPath: '/pglite'
      preLoaderRoute: typeof DashboardPgliteLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/pglite/': {
      id: '/_dashboard/pglite/'
      path: '/'
      fullPath: '/pglite/'
      preLoaderRoute: typeof DashboardPgliteIndexRouteImport
      parentRoute: typeof DashboardPgliteLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardPgliteLayoutRouteChildren {
  DashboardPgliteIndexRoute: typeof DashboardPgliteIndexRoute
}

const DashboardPgliteLayoutRouteChildren: DashboardPgliteLayoutRouteChildren = {
  DashboardPgliteIndexRoute: DashboardPgliteIndexRoute,
}

const DashboardPgliteLayoutRouteWithChildren =
  DashboardPgliteLayoutRoute._addFileChildren(
    DashboardPgliteLayoutRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardPgliteLayoutRoute: typeof DashboardPgliteLayoutRouteWithChildren
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardPgliteLayoutRoute: DashboardPgliteLayoutRouteWithChildren,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthGithubRoute: typeof AuthGithubRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthGithubRoute: AuthGithubRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  TestIndexRoute: TestIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
