/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTwoRouteImport } from './routes/dashboard/two'
import { Route as DashboardThreeRouteImport } from './routes/dashboard/three'
import { Route as DashboardOneRouteImport } from './routes/dashboard/one'
import { Route as DashboardFourRouteImport } from './routes/dashboard/four'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardTwoRoute = DashboardTwoRouteImport.update({
  id: '/two',
  path: '/two',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardThreeRoute = DashboardThreeRouteImport.update({
  id: '/three',
  path: '/three',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardOneRoute = DashboardOneRouteImport.update({
  id: '/one',
  path: '/one',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardFourRoute = DashboardFourRouteImport.update({
  id: '/four',
  path: '/four',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/four': typeof DashboardFourRoute
  '/dashboard/one': typeof DashboardOneRoute
  '/dashboard/three': typeof DashboardThreeRoute
  '/dashboard/two': typeof DashboardTwoRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/four': typeof DashboardFourRoute
  '/dashboard/one': typeof DashboardOneRoute
  '/dashboard/three': typeof DashboardThreeRoute
  '/dashboard/two': typeof DashboardTwoRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/four': typeof DashboardFourRoute
  '/dashboard/one': typeof DashboardOneRoute
  '/dashboard/three': typeof DashboardThreeRoute
  '/dashboard/two': typeof DashboardTwoRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/four'
    | '/dashboard/one'
    | '/dashboard/three'
    | '/dashboard/two'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/four'
    | '/dashboard/one'
    | '/dashboard/three'
    | '/dashboard/two'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/four'
    | '/dashboard/one'
    | '/dashboard/three'
    | '/dashboard/two'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/two': {
      id: '/dashboard/two'
      path: '/two'
      fullPath: '/dashboard/two'
      preLoaderRoute: typeof DashboardTwoRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/three': {
      id: '/dashboard/three'
      path: '/three'
      fullPath: '/dashboard/three'
      preLoaderRoute: typeof DashboardThreeRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/one': {
      id: '/dashboard/one'
      path: '/one'
      fullPath: '/dashboard/one'
      preLoaderRoute: typeof DashboardOneRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/four': {
      id: '/dashboard/four'
      path: '/four'
      fullPath: '/dashboard/four'
      preLoaderRoute: typeof DashboardFourRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardFourRoute: typeof DashboardFourRoute
  DashboardOneRoute: typeof DashboardOneRoute
  DashboardThreeRoute: typeof DashboardThreeRoute
  DashboardTwoRoute: typeof DashboardTwoRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardFourRoute: DashboardFourRoute,
  DashboardOneRoute: DashboardOneRoute,
  DashboardThreeRoute: DashboardThreeRoute,
  DashboardTwoRoute: DashboardTwoRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
