/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthGithubRouteImport } from './routes/auth/github'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardMapsLayoutRouteImport } from './routes/_dashboard/maps/layout'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardMapsIndexRouteImport } from './routes/_dashboard/maps/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardMapsNewRouteImport } from './routes/_dashboard/maps/new'
import { Route as DashboardMapsIdIndexRouteImport } from './routes/_dashboard/maps/$id/index'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthGithubRoute = AuthGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardMapsLayoutRoute = DashboardMapsLayoutRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardMapsIndexRoute = DashboardMapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMapsLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMapsNewRoute = DashboardMapsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardMapsLayoutRoute,
} as any)
const DashboardMapsIdIndexRoute = DashboardMapsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => DashboardMapsLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/maps': typeof DashboardMapsLayoutRouteWithChildren
  '/dashboard': typeof DashboardDashboardRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/test/': typeof TestIndexRoute
  '/maps/new': typeof DashboardMapsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/maps/': typeof DashboardMapsIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/maps/$id/': typeof DashboardMapsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth': typeof AuthIndexRoute
  '/test': typeof TestIndexRoute
  '/maps/new': typeof DashboardMapsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/maps': typeof DashboardMapsIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/maps/$id': typeof DashboardMapsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/_dashboard/maps': typeof DashboardMapsLayoutRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/test/': typeof TestIndexRoute
  '/_dashboard/maps/new': typeof DashboardMapsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/maps/': typeof DashboardMapsIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/maps/$id/': typeof DashboardMapsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/maps'
    | '/dashboard'
    | '/auth/github'
    | '/auth/signup'
    | '/auth/'
    | '/test/'
    | '/maps/new'
    | '/api/auth/$'
    | '/maps/'
    | '/settings/'
    | '/maps/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/github'
    | '/auth/signup'
    | '/auth'
    | '/test'
    | '/maps/new'
    | '/api/auth/$'
    | '/maps'
    | '/settings'
    | '/maps/$id'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/maps'
    | '/_dashboard/dashboard'
    | '/auth/github'
    | '/auth/signup'
    | '/auth/'
    | '/test/'
    | '/_dashboard/maps/new'
    | '/api/auth/$'
    | '/_dashboard/maps/'
    | '/_dashboard/settings/'
    | '/_dashboard/maps/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  TestIndexRoute: typeof TestIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/github': {
      id: '/auth/github'
      path: '/github'
      fullPath: '/auth/github'
      preLoaderRoute: typeof AuthGithubRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/maps': {
      id: '/_dashboard/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof DashboardMapsLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/maps/': {
      id: '/_dashboard/maps/'
      path: '/'
      fullPath: '/maps/'
      preLoaderRoute: typeof DashboardMapsIndexRouteImport
      parentRoute: typeof DashboardMapsLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/maps/new': {
      id: '/_dashboard/maps/new'
      path: '/new'
      fullPath: '/maps/new'
      preLoaderRoute: typeof DashboardMapsNewRouteImport
      parentRoute: typeof DashboardMapsLayoutRoute
    }
    '/_dashboard/maps/$id/': {
      id: '/_dashboard/maps/$id/'
      path: '/$id'
      fullPath: '/maps/$id/'
      preLoaderRoute: typeof DashboardMapsIdIndexRouteImport
      parentRoute: typeof DashboardMapsLayoutRoute
    }
  }
}

interface DashboardMapsLayoutRouteChildren {
  DashboardMapsNewRoute: typeof DashboardMapsNewRoute
  DashboardMapsIndexRoute: typeof DashboardMapsIndexRoute
  DashboardMapsIdIndexRoute: typeof DashboardMapsIdIndexRoute
}

const DashboardMapsLayoutRouteChildren: DashboardMapsLayoutRouteChildren = {
  DashboardMapsNewRoute: DashboardMapsNewRoute,
  DashboardMapsIndexRoute: DashboardMapsIndexRoute,
  DashboardMapsIdIndexRoute: DashboardMapsIdIndexRoute,
}

const DashboardMapsLayoutRouteWithChildren =
  DashboardMapsLayoutRoute._addFileChildren(DashboardMapsLayoutRouteChildren)

interface DashboardLayoutRouteChildren {
  DashboardMapsLayoutRoute: typeof DashboardMapsLayoutRouteWithChildren
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardMapsLayoutRoute: DashboardMapsLayoutRouteWithChildren,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthGithubRoute: typeof AuthGithubRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthGithubRoute: AuthGithubRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  TestIndexRoute: TestIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
